//go:build ignore
// +build ignore

// TEMPORARY AUTOGENERATED FILE: easyjson bootstapping code to launch
// the actual generator.

package main

import (
	"fmt"
	"os"

	"github.com/mailru/easyjson/gen"

	pkg "Class46"
)

func main() {
	g := gen.NewGenerator("json_easyjson.go")
	g.SetPkg("main", "Class46")
	g.Add(pkg.EasyJSON_exporter_Person(nil))
	if err := g.Run(os.Stdout); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
