// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package main

import (
	"github.com/mailru/easyjson/jlexer"
	"github.com/mailru/easyjson/jwriter"
)

func (Person) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*Person) UnmarshalJSON([]byte) error        { return nil }
func (Person) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*Person) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Person *Person
